import {
  DemoUser,
  ReturnRequest,
  TriageLog,
  ActionPack,
  ApiResponse,
  SortDir,
  CHART_DATA_TYPE,
  RECENT_ACTIVITY_TYPE,
  STATS_TYPE,
} from './types'

export const DEMO_USER: DemoUser = {
  id: 'usr-sarah-chen',
  name: 'Sarah Chen',
  email: 'sarah.chen@example.com',
  role: 'E-commerce Ops Manager',
  plan: 'Pro Plan',
  avatar: 'SC',
  joinedAt: '2024-03-10T10:00:00Z',
}

export const MOCK_RETURN_REQUESTS: ReturnRequest[] = [
  {
    id: 'rtn-req-001',
    createdAt: '2024-07-28T09:15:00Z',
    updatedAt: '2024-07-28T09:30:00Z',
    storeId: 'store-alpha-1',
    shopifyOrderId: 'SHOPIFY-78901',
    customerEmail: 'alice.smith@mail.com',
    productName: 'Premium Wireless Headphones',
    productSku: 'HEAD-WIRE-PREM',
    quantity: 1,
    reasonForReturn: 'Item too small for recipient',
    returnStatus: 'Pending Review',
    resolution: 'Pending',
    assignedTo: DEMO_USER.id,
    priority: 'High',
    notes: 'Customer contacted support directly, expecting immediate resolution.',
  },
  {
    id: 'rtn-req-002',
    createdAt: '2024-07-27T14:30:00Z',
    updatedAt: '2024-07-28T10:00:00Z',
    storeId: 'store-alpha-1',
    shopifyOrderId: 'SHOPIFY-78902',
    customerEmail: 'bob.johnson@email.com',
    productName: 'Ceramic Coffee Mug (Set of 2)',
    productSku: 'MUG-CERA-SET',
    quantity: 1,
    reasonForReturn: 'Received damaged product',
    returnStatus: 'Approved',
    resolution: 'Refund',
    assignedTo: DEMO_USER.id,
    priority: 'Urgent',
    notes: 'Photos of damage provided. Refund processed. Awaiting return shipping label confirmation.',
  },
  {
    id: 'rtn-req-003',
    createdAt: '2024-07-26T11:00:00Z',
    updatedAt: '2024-07-27T16:45:00Z',
    storeId: 'store-beta-2',
    shopifyOrderId: 'SHOPIFY-78903',
    customerEmail: 'charlie.brown@web.net',
    productName: 'Ergonomic Desk Chair',
    productSku: 'CHAIR-DESK-ERG',
    quantity: 1,
    reasonForReturn: 'Changed mind, no longer needed',
    returnStatus: 'Rejected',
    resolution: 'No Resolution',
    assignedTo: 'usr-mark-davis', // Another mock user
    priority: 'Low',
    notes: 'Return window expired. Customer notified.',
  },
  {
    id: 'rtn-req-004',
    createdAt: '2024-07-25T18:00:00Z',
    updatedAt: '2024-07-28T08:00:00Z',
    storeId: 'store-alpha-1',
    shopifyOrderId: 'SHOPIFY-78904',
    customerEmail: 'diana.miller@inbox.com',
    productName: 'Smart Home Lighting Kit',
    productSku: 'LIGHT-SMART-KIT',
    quantity: 1,
    reasonForReturn: 'Product not compatible with existing setup',
    returnStatus: 'Closed',
    resolution: 'Exchange',
    assignedTo: DEMO_USER.id,
    priority: 'Medium',
    notes: 'Exchanged for a compatible model. Customer happy with resolution. Case closed.',
  },
  {
    id: 'rtn-req-005',
    createdAt: '2024-07-24T09:45:00Z',
    updatedAt: '2024-07-24T10:15:00Z',
    storeId: 'store-beta-2',
    shopifyOrderId: 'SHOPIFY-78905',
    customerEmail: 'eve.davis@online.org',
    productName: 'Organic Cotton T-Shirt (Large)',
    productSku: 'TEE-ORG-L',
    quantity: 2,
    reasonForReturn: 'Wrong size shipped',
    returnStatus: 'Pending Review',
    resolution: 'Pending',
    assignedTo: DEMO_USER.id,
    priority: 'High',
    notes: 'Verified shipping error. Initiating exchange for correct size. Awaiting stock confirmation.',
  },
  {
    id: 'rtn-req-006',
    createdAt: '2024-07-23T16:20:00Z',
    updatedAt: '2024-07-23T16:20:00Z',
    storeId: 'store-gamma-3',
    shopifyOrderId: 'SHOPIFY-78906',
    customerEmail: 'frank.white@site.net',
    productName: 'Portable Bluetooth Speaker',
    productSku: 'SPKR-BT-PORT',
    quantity: 1,
    reasonForReturn: 'Product not as described',
    returnStatus: 'Cancelled',
    resolution: 'No Resolution',
    assignedTo: null,
    priority: 'Low',
    notes: 'Customer cancelled request before processing. No action needed.',
  },
]

export const MOCK_TRIAGE_LOGS: TriageLog[] = [
  {
    id: 'tlg-001',
    createdAt: '2024-07-28T09:30:00Z',
    updatedAt: '2024-07-28T09:30:00Z',
    returnRequestId: 'rtn-req-001',
    userId: DEMO_USER.id,
    action: 'Assigned to self',
    details: 'Return request #SHOPIFY-78901 assigned to Sarah Chen for review.',
  },
  {
    id: 'tlg-002',
    createdAt: '2024-07-28T10:00:00Z',
    updatedAt: '2024-07-28T10:00:00Z',
    returnRequestId: 'rtn-req-002',
    userId: DEMO_USER.id,
    action: 'Updated status to Approved',
    details: 'Status changed to Approved. Resolution set to Refund due to product damage.',
  },
  {
    id: 'tlg-003',
    createdAt: '2024-07-27T16:45:00Z',
    updatedAt: '2024-07-27T16:45:00Z',
    returnRequestId: 'rtn-req-003',
    userId: 'usr-mark-davis',
    action: 'Updated status to Rejected',
    details: 'Return request #SHOPIFY-78903 rejected as return window passed.',
  },
  {
    id: 'tlg-004',
    createdAt: '2024-07-28T08:00:00Z',
    updatedAt: '2024-07-28T08:00:00Z',
    returnRequestId: 'rtn-req-004',
    userId: DEMO_USER.id,
    action: 'Updated status to Closed',
    details: 'Exchanged product shipped. Return request #SHOPIFY-78904 closed.',
  },
  {
    id: 'tlg-005',
    createdAt: '2024-07-24T10:15:00Z',
    updatedAt: '2024-07-24T10:15:00Z',
    returnRequestId: 'rtn-req-005',
    userId: DEMO_USER.id,
    action: 'Added note',
    details: 'Confirmed wrong size was shipped. Initiating exchange process.',
  },
  {
    id: 'tlg-006',
    createdAt: '2024-07-23T16:20:00Z',
    updatedAt: '2024-07-23T16:20:00Z',
    returnRequestId: 'rtn-req-006',
    userId: null, // Customer action
    action: 'Return request cancelled',
    details: 'Customer cancelled the return request directly via portal.',
  },
]

export const MOCK_ACTION_PACKS: ActionPack[] = [
  {
    id: 'act-pck-001',
    createdAt: '2024-07-28T11:00:00Z',
    updatedAt: '2024-07-28T11:00:00Z',
    name: 'Daily High Priority Returns - July 28',
    description: 'All high and urgent priority return requests requiring action today.',
    returnRequestIds: ['rtn-req-001', 'rtn-req-002', 'rtn-req-005'],
    status: 'Generated',
    generatedBy: DEMO_USER.id,
    exportUrl: '/exports/daily-high-priority-returns-jul28.csv',
  },
  {
    id: 'act-pck-002',
    createdAt: '2024-07-26T15:30:00Z',
    updatedAt: '2024-07-26T15:35:00Z',
    name: 'Weekly Pending Reviews - Week 30',
    description: 'All return requests still in "Pending Review" status from the past week.',
    returnRequestIds: ['rtn-req-001', 'rtn-req-005'],
    status: 'Downloaded',
    generatedBy: DEMO_USER.id,
    exportUrl: '/exports/weekly-pending-reviews-wk30.csv',
  },
  {
    id: 'act-pck-003',
    createdAt: '2024-07-25T10:00:00Z',
    updatedAt: '2024-07-25T10:00:00Z',
    name: 'Damaged Items Report - Q3-24',
    description: 'Summary of all return requests due to damaged items in Q3.',
    returnRequestIds: ['rtn-req-002'],
    status: 'Archived',
    generatedBy: 'usr-mark-davis',
    exportUrl: '/exports/damaged-items-q3-24.pdf',
  },
  {
    id: 'act-pck-004',
    createdAt: '2024-07-24T08:00:00Z',
    updatedAt: '2024-07-24T08:00:00Z',
    name: 'Customer Service Escalations - July',
    description: 'Returns that involved direct customer service contact and escalation.',
    returnRequestIds: ['rtn-req-001'],
    status: 'Generated',
    generatedBy: DEMO_USER.id,
    exportUrl: '/exports/cs-escalations-jul.xlsx',
  },
  {
    id: 'act-pck-005',
    createdAt: '2024-07-22T14:00:00Z',
    updatedAt: '2024-07-22T14:00:00Z',
    name: 'Expired Return Window Notifs',
    description: 'Report of requests rejected due to expired return windows.',
    returnRequestIds: ['rtn-req-003'],
    status: 'Draft',
    generatedBy: DEMO_USER.id,
    exportUrl: '/exports/expired-returns-notifs.csv',
  },
  {
    id: 'act-pck-006',
    createdAt: '2024-07-21T09:00:00Z',
    updatedAt: '2024-07-21T09:00:00Z',
    name: 'SKU Compatibility Issues Report',
    description: 'Requests related to product compatibility issues across stores.',
    returnRequestIds: ['rtn-req-004'],
    status: 'Generated',
    generatedBy: 'usr-mark-davis',
    exportUrl: '/exports/sku-compatibility-report.json',
  },
]

export const STATS: STATS_TYPE = {
  totalReturnsValue: '$184,350',
  pendingRequests: 18,
  resolutionRate: '92.3%',
  highPriorityToday: 7,
}

export const CHART_DATA: CHART_DATA_TYPE = {
  weekly: [42, 58, 51, 73, 88, 65, 79, 94], // New return requests
  labels: ['Jan W1', 'Jan W2', 'Jan W3', 'Jan W4', 'Feb W1', 'Feb W2', 'Feb W3', 'Feb W4'],
  revenue: [18200, 22400, 19800, 31200, 28500, 33100, 29800, 35600], // Total value of processed returns ($)
}

export const RECENT_ACTIVITY: RECENT_ACTIVITY_TYPE[] = [
  {
    id: '1',
    action: 'Assigned request #SHOPIFY-78901 to self',
    user: 'Sarah Chen',
    avatar: 'SC',
    time: '2 minutes ago',
    type: 'update',
  },
  {
    id: '2',
    action: 'Approved request #SHOPIFY-78902 for refund',
    user: 'Sarah Chen',
    avatar: 'SC',
    time: '1 hour ago',
    type: 'update',
  },
  {
    id: '3',
    action: 'Generated "Daily High Priority Returns" action pack',
    user: 'Sarah Chen',
    avatar: 'SC',
    time: '3 hours ago',
    type: 'export',
  },
  {
    id: '4',
    action: 'Closed request #SHOPIFY-78904 after exchange',
    user: 'Sarah Chen',
    avatar: 'SC',
    time: 'Yesterday at 11:30 AM',
    type: 'update',
  },
  {
    id: '5',
    action: 'Rejected request #SHOPIFY-78903 - expired window',
    user: 'Mark Davis',
    avatar: 'MD',
    time: 'Yesterday at 3:15 PM',
    type: 'delete',
  },
  {
    id: '6',
    action: 'Created new return request #SHOPIFY-78901',
    user: 'Alice Smith (Customer)',
    avatar: 'AS',
    time: '2 days ago',
    type: 'create',
  },
]

export function getById<T extends { id: string }>(arr: T[], id: string): T | undefined {
  return arr.find((x) => x.id === id)
}